### ISSUE TITLE
Create remote cec-client module

### ISSUE THREAD

**Issue by TB-1993** [rdkcentral/python_raft#107]
### Description:

**Problem/Opportunity:** It would be nice to be able to run the cec-client off a remote device connected to the DUT, rather than the host machine.

**Proposed Solution:** To remotely test a DUT a device would need to be connected to that could be remotely controlled, such as a Raspberry Pi. If this device had cec-utils installed, it could be used to remotely run the cec-client and send CEC messages to the DUT.

### Acceptance Criteria: (Optional)
* A remotely controllable version of the cec-client is created that correctly implements all the methods outline in the abstract cec class.

**Comment by Ulrond** [comment]
? What's this for Seems duplication?
