### ISSUE TITLE
HTTP requests module to raft

### ISSUE THREAD

**Issue by barbourshop** [rdkcentral/python_raft#22]
## Goal: Create an http request control module
This task would be to create a control module that users could be used to make http requests from tests in a standardised manner.

## Acceptance Criteria:
- http_requests module exists that can be used in the tests, providing the following http requests method:
  - get
  - put
  - post
  - head
- Responses from the above methods should be returned in a standardised object with all the information from the response to the request.

**Comment by TB-1993** [comment]
I don't think this actually necessary. I think people can just use the python requests module to make their requests directly. Rather than using the same thing wrapped as a raft module.
