### ISSUE TITLE
python_raft: add device: CEC Adapter in the core supported modules.

### ISSUE THREAD

**Issue by Ulrond** [rdkcentral/python_raft#79]
## Goals

- Create a wrapper for Support for the `CEC_Apapter` as a device in `python-raft`

 The link to the software installation is here [https://android.googlesource.com/platform/cts/+/refs/heads/main/hostsidetests/hdmicec/cec_adapter.md](https://android.googlesource.com/platform/cts/+/refs/heads/main/hostsidetests/hdmicec/cec_adapter.md)

*Briefly describe the purpose of the milestone and its impact on the project.*

## Key Deliverables

* [ ] Wrap the above API into the python_raft supported devices
* [ ] Ensure that any install scripts installs the host requirements, or includes a binary version of the tool
* [ ] Write a framework test that proves the integration of the module.

## Exit Criteria

* Basic framework test is passing and the module is controllable
* Clean installation with the supported external dependencies are met

### Dependencies

* Download and installation of the tool on the host system

### UpLink Data

* **Jira:** <project>-<id>  
    * This Jira issue details the user story that directly aligns with this milestone's goals and deliverables.
    * Include the Jira ID for easy reference and tracking.

**Comment by TB-1993** [comment]
I accidentally duplicated this with #92, which is now under review #105. Closing this ticket as duplicate.
