### ISSUE TITLE
documentation: make clear that default console should not be ssh or telnet

### ISSUE THREAD

**Issue by Ulrond** [rdkcentral/python_raft#82]
The documentation and example configuration should emphasize that the default session should not be set to **SSH** or **Telnet** if you require complete control over the lifecycle of the device under test.

**SSH** and **Telnet** protocols necessitate that the device is powered on and operational. During framework initialisation, the default session is automatically started, if the device is offline or hasn't finished booting, this connection will fail.

To use **SSH** exclusively, you must configure the default console as **empty**, since any attempt to communicate with an offline device would be unsuccessful. Subsequently, you'd manually initiate the **SSH** session once you can guarantee the device is online, that would be outside the scope of the current framework and would be controlled by the test itself.

Therefore, it's strongly recommended to use a serial connection or leave the default session empty to avoid issues during test setup. This guidance should be clearly stated in the documentation.

We need to ensure that the framework also supports a default session as empty.

**Comment by TB-1993** [comment]
I'm going to reject this ticket as I believe fixing up the consoles as we are in #95 should alleviate the need for it.
