### ISSUE TITLE
ModuleNotFoundError: No module named 'framework.core.powerModules.S20control'

### ISSUE THREAD

**Issue by jamcoole** [rdkcentral/python_raft#83]
cloning the code and setting up requirements on first run you get a module not found error 

`Traceback (most recent call last):
  File "/home/jenkins/RAFT/python_raft/examples/code/example_ssh.py", line 40, in <module>
    from framework.core.testControl import testController
  File "/home/jenkins/RAFT/python_raft/examples/code/../../framework/core/__init__.py", line 37, in <module>
    from . deviceManager import deviceManager
  File "/home/jenkins/RAFT/python_raft/examples/code/../../framework/core/deviceManager.py", line 38, in <module>
    from framework.core.powerControl import powerControlClass
  File "/home/jenkins/RAFT/python_raft/examples/code/../../framework/core/powerControl.py", line 48, in <module>
    from framework.core.powerModules.S20control import powerOrviboS20
ModuleNotFoundError: No module named 'framework.core.powerModules.S20control'
jenkins@raven:~/RAFT/python_raft/examples/code$`

I removed it to get past the error:

diff --git a/framework/core/powerControl.py b/framework/core/powerControl.py
index d10d5d4..95ba881 100644
--- a/framework/core/powerControl.py
+++ b/framework/core/powerControl.py
@@ -45,7 +45,6 @@
 #     7- Cancel
 ###########################################################

-from framework.core.powerModules.S20control import powerOrviboS20
 from framework.core.powerModules.apcAos import powerApcAos
 from framework.core.powerModules.kasaControl import powerKasa
 from framework.core.powerModules.olimex import powerOlimex
@@ -80,8 +79,6 @@ class powerControlClass():
         type = config.get("type")
         if type == None:
             self.powerSwitch = powerNone( log )
-        elif type == "orviboS20":
-            self.powerSwitch = powerOrviboS20( log, ip=self.ip, mac=config.get("mac"), port=config.get("port"))
         elif type == "hs100":
             self.powerSwitch = powerHS100( log, self.ip, config.get("port"))
         elif type == "apc":

**Comment by TB-1993** [comment]
This was fixed as part of 1.1.0.
