### ISSUE TITLE
Standardise waitForPrompt and write methods

### ISSUE THREAD

**Issue by TB-1993** [rdkcentral/python_raft#96]
### Description:

**Problem/Opportunity:** The `waitForPrompt` method is currently implemented on the `testController` class and only acts upon the DUT. This is leading to users of the framework to writing their own methods to do the same thing for the other devices in their setups.

**Proposed Solution:** Move the `waitForPrompt` method to the abstract console class. The prompt would be pass in to the console class upon initialisation. This would allow for all consoles to work the same waiting for prompt, regardless of device. This would also allow for an upgrade to be made to the `write` method of the console classes, allowing them to optionally wait for a prompt before writing.

### Acceptance Criteria: (Optional)

* The `waitForPrompt` should be a standard method for all console classes
* The `write` method of all console classes should optionally wait for the prompt to return before writing its message into the console.

**Comment by Ulrond** [comment]
Each session should be given a prompt configuration when it starts
